name: Go
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
strategy:
    matrix:
    include:
    - name: windows-amd64-v3
    goos: windows
    goarch: amd64
    goamd64: v3
            
  build:
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      GOARM: ${{ matrix.goarm }}
      GOMIPS: ${{ matrix.gomips }}
      CGO_ENABLED: 0
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.version.outputs.go_version }}
    - name: Cache go module
      uses: actions/cache@v3
      with:
          path: |
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
    - name: Build
      id: build
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: v2box-${{ matrix.name }}
        path: v2box*
